# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pipeline Flask Rendee

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy no EC2 - AWS
      run: |
        echo "Conectando no EC2"
        echo "${{secrets.AWS_PEM}}" > private_key && chmod 600 private_key 
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-44-217-227-243.compute-1.amazonaws.com "
          cd ./flare-att  && git pull  && ../iniciarApp.sh"
